from datasets import Dataset
from abc import ABC
import random
import traceback
from typing import Dict, List, Optional
from synthetic_data.conversion import chatml_to_conversation
from synthetic_data.generation import SHAREGPT_TO_OPENAI_ROLE
from synthetic_data.prompts import (
    TOOL_USE_CATEGORIES,
    format_famous_figures_classifier_system_prompt,
    format_nsfw_classifier_system_prompt,
    format_dalle_prompt_template,
    format_safety_prompt_template,
    get_tool_usage_prompt,
    get_toolformer_dpo_negative_completion_prompt,
    get_toolformer_prompt,
)
from synthetic_data.tools import (
    DROPOUT_TYPES_JSON,
    DROPOUT_TYPES_TOOLFORMER,
    get_tool_description_json,
    get_tool_descriptions,
)
from datasets import Dataset, concatenate_datasets
import pandas as pd


from synthetic_data.utils import (
    Conversation,
    DatasetTaskFormat,
    DatasetFormat,
    SyntheticToolCallRow,
    SyntheticToolCallDPORow,
    ToolFormerDPORow,
    ToolFormerRow,
    extract_label,
    is_valid_python,
    clean_message,
    get_matches,
    ensure_directory,
)

from synthetic_data.labels import SAFERPROMPT_LABELS, FAMOUS_FIGURES_LABELS

class SyntheticDataTask(ABC):

    seed_data_format: DatasetFormat = DatasetFormat.SYNTHETIC
    dataset_task_format: DatasetTaskFormat = DatasetTaskFormat.SFT

    # Only used for the toolformer DPO dataset. # TODO remove this when that project is finished.
    seed_data_uses_conversation_format: bool = False

    # Name for the dataset used to cache the seed data.
    # Once all the seed data is generated, this dataset will be used to cache the seed data.
    dpo_seed_cache_dataset_name: Optional[str] = None

    no_dpo_completions: int = 2

    seed_data_location: str
    output_data_name: str
    output_data_format: DatasetFormat = DatasetFormat.HF_DATASET

    dataset_org: str = "roborovski"

    empty_dataset_format: Dict[str, List]
    empty_dpo_dataset_format: Dict[str, List]

    original_rows_batch = []

    def format_seed_input_conversation(self, batch: Dict) -> List[Conversation]:
        """
        Prompt template to use for generating initial seed data.
        """
        raise NotImplementedError

    def get_seed_dataset_output_rows_batch(self, completions: List[str]) -> List[Dict]:
        """
        Take the completed conversation and format it into the final dataset format.
        """
        raise NotImplementedError

    def format_dpo_input_conversations(self, batch: Dict) -> List[Conversation]:
        """
        Format conversation for DPO negative that will be generated by the LLM.
        """
        raise NotImplementedError

    def get_dpo_dataset_output_batch(self, completions: List[str]) -> List[Dict]:
        """
        Take the completed conversation and format it into the final dataset format.
        """
        raise NotImplementedError

    def preprocess_dataset(self, dataset: Dataset) -> Dataset:
        """
        Perform any needed filtering or mapping to the dataset
        """
        return dataset


class PromptUpsample(SyntheticDataTask):

    seed_data_format = DatasetFormat.CSV
    seed_data_location = "data/PartiPrompts.tsv"
    output_data_name = "upsampled-prompts-parti"
    dataset_task_format = DatasetTaskFormat.SFT

    empty_dataset_format = {
        "Prompt": [],
        "Category": [],
        "Upsampled": [],
    }

    def format_seed_input_conversation(self, batch: Dict) -> List[Conversation]:
        prompts = batch["Prompt"]
        return [format_dalle_prompt_template(prompt) for prompt in prompts]


def preprocess_prompts(row: Dict) -> bool:
    prompt: str = row["prompt"]
    if not prompt:
        return False
    if len(prompt) == 0:
        return False
    if len(prompt.split(" ")) > 128:
        return False
    if len(prompt) > 256:
        return False
    return True


class PromptRewritingDPO(SyntheticDataTask):

    seed_data_format = DatasetFormat.PARQUET
    seed_data_location = "data/nsfw_prompts.parquet"
    output_data_name = "safer-prompt"
    output_data_format = DatasetFormat.CSV
    dataset_task_format = DatasetTaskFormat.SFT

    empty_dataset_format = {
        "Prompt": [],
        "Sanitized": [],
    }

    def preprocess_dataset(self, dataset: Dataset) -> Dataset:
        dataset = dataset.filter(preprocess_prompts)
        return dataset

    def format_seed_input_conversation(self, batch: Dict) -> List[Conversation]:
        prompts = batch["prompt"]
        self.original_rows_batch = prompts
        return [format_safety_prompt_template(prompt) for prompt in prompts]

    def get_seed_dataset_output_rows_batch(self, completions: List[str]) -> List[Dict]:
        rows = []
        for completion, original_row in zip(completions, self.original_rows_batch):
            if completion == "":
                continue
            if "I'm sorry" in completion:
                continue
            completion = clean_message(completion)
            rows.append({"Prompt": original_row, "Sanitized": completion})
        return rows


class SafetyLabeling(SyntheticDataTask):

    seed_data_format = DatasetFormat.CSV
    seed_data_location = "data_files/160k_batch1.tsv"
    output_data_name = "safer-prompt"
    output_data_format = DatasetFormat.CSV
    dataset_task_format = DatasetTaskFormat.SFT
    dataset_labels = SAFERPROMPT_LABELS

    empty_dataset_format = {
        "prompt": [],
        "annotated_label": [],
        "class_label": [],
    }

    def preprocess_dataset(self, dataset: Dataset) -> Dataset:
        """
        Evenly sample the dataset to have the same number of samples per class.
        """
        dataset = dataset.filter(preprocess_prompts)
        pd_dataset: pd.DataFrame = dataset.to_pandas()  # type: ignore
        pd_dataset["tasks_label"] = pd_dataset["tasks_label"].replace(
            "borderline", "unsafe"
        )
        max_samples_per_group: int = pd_dataset.groupby("tasks_label").size().min()  # type: ignore

        def sample_group(group):
            return group.sample(min(len(group), max_samples_per_group))

        print(
            f"Sampling {max_samples_per_group} samples per class from dataset of length {len(dataset)}"
        )
        print(
            f"Original class distribution: {pd_dataset.groupby('tasks_label').size()}"
        )
        sampled_df = pd_dataset.groupby("tasks_label", group_keys=False).apply(
            sample_group
        )

        sampled_dataset = Dataset.from_pandas(sampled_df)  # type: ignore
        return sampled_dataset

    def format_seed_input_conversation(self, batch: Dict) -> List[Conversation]:
        self.original_rows_batch = batch
        return [
            format_nsfw_classifier_system_prompt(prompt) for prompt in batch["prompt"]
        ]

    def get_seed_dataset_output_rows_batch(self, completions: List[str]) -> List[Dict]:
        rows = []
        for completion, prompt, task_label in zip(
            completions,
            self.original_rows_batch["prompt"],
            self.original_rows_batch["tasks_label"],
        ):
            if completion == "":
                continue
            if "I'm sorry" in completion:
                continue
            completion = clean_message(completion)
            class_label = extract_label(completion, self.dataset_labels)
            if not class_label:
                continue
            rows.append(
                {
                    "prompt": prompt,
                    "annotated_label": task_label,
                    "class_label": class_label,
                }
            )
        return rows


class FamousFiguresLabeling(SafetyLabeling):

    dataset_labels = FAMOUS_FIGURES_LABELS
    output_data_name = "famous-figures-labeling"

    def format_seed_input_conversation(self, batch: Dict) -> List[Conversation]:
        self.original_rows_batch = batch
        return [
            format_famous_figures_classifier_system_prompt(prompt) for prompt in batch["prompt"]
        ]


class Toolformer(SyntheticDataTask):

    seed_data_format = DatasetFormat.SYNTHETIC
    seed_data_location = "data_files/domain_specific_tasks.csv"

    dataset_task_format = DatasetTaskFormat.DPO

    dpo_seed_cache_dataset_name = "synthetic-toolformer-sharegpt"

    output_data_name = "synthetic-toolformer-dpo"

    empty_dataset_format = {
        "system": [],
        "question": [],
        "chosen": [],
        "rejected": [],
    }

    original_rows_batch: List[ToolFormerRow] = []

    def format_seed_input_conversation(self, batch_size: int) -> List[Conversation]:
        prompt_conversations: List[Conversation] = []
        random_categories = random.sample(TOOL_USE_CATEGORIES * batch_size, batch_size)
        tool_descriptions = get_tool_descriptions()
        for category in random_categories:
            prompt_conversations.append(
                get_toolformer_prompt(category, tool_descriptions)
            )
        return prompt_conversations

    def get_seed_dataset_output_rows_batch(self, completions_batch: List[str]) -> Dict:
        for completion in completions_batch:
            question, tool_call, call_result, agent_output = get_matches(completion)
            row = ToolFormerRow(question, tool_call, call_result, agent_output)

            assert is_valid_python(row.call_result)
            assert is_valid_python(row.tool_call)

        return {
            "call_result": row.call_result,
            "tool_call": row.tool_call,
            "agent_output": row.agent_output,
        }

    def format_dpo_input_conversations(self, batch: Dict) -> List[Conversation]:

        conversations = batch["conversations"]

        dropout_types_batch = random.choices(
            DROPOUT_TYPES_TOOLFORMER, k=len(conversations)
        )

        conversations_batch: List[Conversation] = []
        original_rows_batch: List[ToolFormerRow] = []
        for i, conversation in enumerate(conversations):
            messages = [message["content"] for message in conversation]
            for _ in range(self.no_dpo_completions):
                question, tool_call, call_result, agent_output = messages
                original_row = ToolFormerRow(
                    question=question,
                    call_result=call_result,
                    tool_call=tool_call,
                    agent_output=agent_output,
                )
                tool_descriptions = get_tool_descriptions(dropout_types_batch[i])
                conversation = get_toolformer_dpo_negative_completion_prompt(
                    question, tool_descriptions
                )
                conversations_batch.append(conversation)
                original_rows_batch.append(original_row)
        self.original_rows_batch = original_rows_batch
        return conversations_batch

    def get_dpo_dataset_output_batch(self, completions_batch: List[str]) -> List[Dict]:

        # Get completions for each prompt, rank, and choos the 2 highest
        new_rows_batch = []
        dpo_rows_batch: List[ToolFormerRow] = []
        for completion, original_row in zip(
            completions_batch, self.original_rows_batch
        ):
            try:
                tool_call, call_result, agent_output = get_matches(completion)

                dpo_row = ToolFormerRow(
                    original_row.question,
                    call_result,
                    tool_call,
                    agent_output,
                )

                dpo_rows_batch.append(dpo_row)

                if dpo_row.tool_call == original_row.tool_call:
                    continue

                output_row = ToolFormerDPORow(
                    question=original_row.question,
                    call_result_accepted=original_row.call_result,
                    tool_call_accepted=original_row.tool_call,
                    agent_output_accepted=original_row.agent_output,
                    call_result_rejected=call_result,
                    tool_call_rejected=tool_call,
                    agent_output_rejected=agent_output,
                )

                row_dict = output_row.__dict__
                new_rows_batch.append(row_dict)
            except Exception as e:
                print(f"Error in parsing completion: {e}")
                continue

        return new_rows_batch


class SyntheticToolCalls(SyntheticDataTask):

    dataset_task_format = DatasetTaskFormat.DPO
    seed_data_format = DatasetFormat.CSV
    seed_data_location = "data_files/domain_specific_tasks.csv"

    # TODO swap this and the output dataset name
    dpo_seed_cache_dataset_name = "synthetic-tool-calls-dpo-pairs"

    output_data_name = "synthetic-tool-calls-v2-dpo-pairs"

    empty_dataset_format = {
        "tool": [],
        "question": [],
        "call_result": [],
        "tool_call": [],
    }

    empty_dpo_dataset_format = {
        "tool": [],
        "question": [],
        "tool_call_accepted": [],
        "call_result_accepted": [],
        "agent_output_accepted": [],
        "tool_call_rejected": [],
        "call_result_rejected": [],
        "agent_output_rejected": [],
    }

    original_rows_batch: List[SyntheticToolCallRow] = []

    def format_seed_input_conversation(self, batch: Dict) -> List[Conversation]:
        conversations = []
        for category, task in zip(batch["Category"], batch["Task"]):
            conversations.append(get_tool_usage_prompt(category, task))
        return conversations

    def get_seed_dataset_output_rows_batch(
        self, completions_batch: List[str]
    ) -> List[Dict]:
        batch = []
        for completion in completions_batch:
            try:
                _, tool, question, tool_call, call_result, agent_output = get_matches(
                    completion
                )

                row = SyntheticToolCallRow(
                    tool, question, tool_call, call_result, agent_output
                )

                assert is_valid_python(row.call_result)
                assert is_valid_python(row.tool_call)

                batch.append(
                    {
                        "tool": row.tool,
                        "question": row.question,
                        "call_result": row.call_result,
                        "tool_call": row.tool_call,
                        "agent_output": row.agent_output,
                    }
                )
            except Exception as e:
                print(f"Error in parsing seed completion: {e}")
                continue
        return batch

    def format_dpo_input_conversations(self, batch: Dict) -> List[Conversation]:

        n_samples = len(batch["tool"])
        dropout_types_batch = random.choices(DROPOUT_TYPES_JSON, k=n_samples)

        conversations_batch: List[Conversation] = []
        original_rows_batch: List[SyntheticToolCallRow] = []
        for i in range(n_samples):
            for _ in range(self.no_dpo_completions):
                try:
                    question = batch["question"][i]
                    tool = batch["tool"][i]
                    original_row = SyntheticToolCallRow(
                        tool=tool,
                        question=question,
                        tool_call=batch["tool_call"][i],
                        call_result=batch["call_result"][i],
                        agent_output=batch["agent_output"][i],
                    )
                    tool_descriptions = get_tool_description_json(
                        tool, dropout_types_batch[i]
                    )
                    conversation = get_toolformer_dpo_negative_completion_prompt(
                        question, tool_descriptions, True
                    )
                    conversations_batch.append(conversation)
                    original_rows_batch.append(original_row)
                except Exception as e:
                    print(f"Error in formatting DPO input: {e}")
                    traceback.print_exc()
                    continue
        self.original_rows_batch = original_rows_batch
        return conversations_batch

    def get_dpo_dataset_output_batch(self, completions_batch: List[str]) -> List[Dict]:

        # Get completions for each prompt, rank, and choos the 2 highest
        new_rows_batch = []
        for completion, original_row in zip(
            completions_batch, self.original_rows_batch
        ):
            try:
                tool_call, call_result, agent_output = get_matches(completion)

                if (
                    tool_call == original_row.tool_call
                    and agent_output == original_row.agent_output
                ):
                    continue

                dpo_row = SyntheticToolCallDPORow(
                    original_row.tool,
                    original_row.question,
                    original_row.tool_call,
                    original_row.call_result,
                    original_row.agent_output,
                    tool_call,
                    call_result,
                    agent_output,
                )
                row_dict = dpo_row.__dict__
                new_rows_batch.append(row_dict)

            except Exception as e:
                traceback.print_exc()
                print(f"Error in parsing completion: {e}")
                continue

        return new_rows_batch


class GlaiveDPO(SyntheticDataTask):
    def format_seed_input_conversation(self, batch: Dict) -> List[Conversation]:
        glaive_conversations = [
            chatml_to_conversation(chat, system)
            for chat, system in zip(batch["chat"], batch["system"])
        ]
        prompt_conversations: List[Conversation] = []
        for conversation in glaive_conversations:
            completion_conv = []
            for msg in conversation:
                if msg["from"] == "gpt":
                    break
                completion_conv.append(
                    {
                        "role": SHAREGPT_TO_OPENAI_ROLE[msg["from"]],
                        "content": msg["value"],
                    }
                )
            prompt_conversations.append(completion_conv)
        return prompt_conversations

    def _clean_glaive_conversation(
        self, completions: List[str], glaive_conversations: List[Dict]
    ) -> List[Dict]:
        new_rows_batch = []
        for completion, glaive_conversation in zip(completions, glaive_conversations):

            system_msg, user_msg, accepted_msg, rejected_msg = (
                "",
                "",
                "",
                "",
            )
            for msg in glaive_conversation:
                role, content = msg["from"], msg["value"]
                if role == "system":
                    system_msg = clean_message(content)
                if role == "human":
                    user_msg = clean_message(content)
                if role == "gpt":
                    accepted_msg = clean_message(content)
                    rejected_msg = completion
                    break
            new_rows_batch.append(
                {
                    "system": system_msg,
                    "question": user_msg,
                    "chosen": accepted_msg,
                    "rejected": rejected_msg,
                }
            )

        # TODO fix
        return [
            {"role": SHAREGPT_TO_OPENAI_ROLE[msg["from"]], "content": msg["value"]}
            for msg in new_rows_batch
        ]


def save_dataset(
    hf_dataset: Dataset, task: SyntheticDataTask, new_dataset_rows: List[Dict]
):
    dataset_new_rows = Dataset.from_list(new_dataset_rows)

    ensure_directory("output_datasets")

    concatenated_dataset = concatenate_datasets([hf_dataset, dataset_new_rows])
    if task.output_data_format == DatasetFormat.HF_DATASET:
        print(f"Uploading {len(new_dataset_rows)} new rows to the Hub...")
        concatenated_dataset.push_to_hub(task.output_data_name)
    elif task.output_data_format == DatasetFormat.PARQUET:
        concatenated_dataset.to_parquet(f"{task.output_data_name}.parquet")
    elif task.output_data_format == DatasetFormat.CSV:
        concatenated_dataset.to_csv(
            f"output_datasets/{task.output_data_name}.csv", index=False
        )
