wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.15.4
    framework: huggingface
    huggingface_version: 4.31.0.dev0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1688237983.220845
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 98
      - 100
      3:
      - 23
      4: 3.8.10
      5: 0.15.4
      6: 4.31.0.dev0
      8:
      - 5
